source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.6'
# A simple, fast Mysql library for Ruby, binding to libmysql
gem 'mysql2', '~> 0.4.10'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Allows you to generate your JSON in an object-oriented and convention-driven manner
gem 'active_model_serializers', '~> 0.10.0'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.0', '>= 1.0.2'
# Autoload dotenv in Rails
gem 'dotenv-rails', '~> 2.2', '>= 2.2.1'
# For use with client side single page apps such as the venerable
gem 'devise_token_auth', '~> 0.1.42'
# Give people feedback about long-running tasks
gem 'progress_bar', '~> 1.2'
# Ancestry allows the records of a ActiveRecord model to be organized in a tree structure
gem 'ancestry', '~> 3.0', '>= 3.0.1'
# Automaticaly increments a string or integer field in ActiveRecord
gem 'auto_increment', '~> 1.5'
# Upload files in your Ruby applications
gem 'carrierwave', '~> 1.2', '>= 1.2.2'
# generate xlsx files
gem 'write_xlsx'
# Excel reading gem
gem 'roo', '~> 2.7.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry', '~> 0.11.3'

  # Faker  is used to easily generate fake data: names, addresses, phone numbers, etc
  gem 'faker', '~> 1.8', '>= 1.8.7'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
